language: go

matrix:
  include:
    - go: 1.8.x
      env:
        - PYTHON_VERSION=2.7
    - go: 1.8.x
      env:
        - CHECK_GOLINT=true
        - PYTHON_VERSION=3.4  # Ubuntu14's python3 = 3.4.x

sudo: required
dist: trusty

notifications:
  email: false

go_import_path: gopkg.in/sensorbee/py.v0

before_install:
  - env
  - lsb_release -a
  - sudo apt-get -qq update
  - if [ "$PYTHON_VERSION" != "2.7" ]; then
      sudo apt-get -qq install python3-pip;
      sudo pip3 install six;
      python3 --version;
    else
      pip install six;
      python --version;
    fi
  - sudo apt-get -qq install pkg-config
  - go version

install:
  - if [ $CHECK_GOLINT ]; then go get golang.org/x/lint/golint; fi
  - go get -a github.com/mattn/goveralls
  - go get -a golang.org/x/tools/cmd/cover
  - go get -a github.com/pierrre/gotestcover
  - go get -t -d -v ./...

before_script:
  - if [ $CHECK_GOLINT ]; then golint ./... | tee .golint.txt && test ! -s .golint.txt; fi

script:
  - if [ "$PYTHON_VERSION" != "2.7" ]; then
      go build -v --tags=py"$PYTHON_VERSION" ./...;
    else
      go build -v ./...;
    fi
  - if [ "$PYTHON_VERSION" != "2.7" ]; then
      gotestcover -v -covermode=count -coverprofile=.profile.cov -parallelpackages=1 --tags=py"$PYTHON_VERSION" ./...;
    else
      gotestcover -v -covermode=count -coverprofile=.profile.cov -parallelpackages=1 ./...;
    fi

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.7.4" ]; then goveralls -coverprofile=.profile.cov -repotoken $COVERALLS_TOKEN; fi
